# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e187737501a7a2635859edaa8b9f8302f852c38109c9720d5b8527a35bced2436c264f28e607c1544ecf794c69e45b272e553c08f273213a22622db374b2ba06

test:
  secret_key_base: 8564489bce709eff74bebe685240067539af4509b2f8366eaced8d99ddb46abd25cead3a153013352adbc8e5021b1db252efd22411b578490d79f73ebca07a84

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
